### PR TITLE
Add big summer files

### PR DESCRIPTION
**Pull request by andrewram4287**

### CODE REVIEW

**Comment by andrewram4287** [comment]
@JacksonLChin is there anything else you'd like to upload to their files?

**Comment by andrewram4287** [comment]
@JacksonLChin

**Comment by JacksonLChin** [comment]
@andrewram4287 Thanks for putting this together! Looks great--just added in a meta-data import.

**Review by JacksonLChin — APPROVED** [review]

**Comment by JacksonLChin** [comment]
@andrewram4287 If the changes I made look good to you, feel free to merge!

**Pull request merged**
